from typing import Protocol

class AgentEventObserver(Protocol):
    def on_turn_start(self): ...
    def on_iteration_start(self, iteration: int, max_iterations: int): ...
    def on_llm_progress(self, info: str): ...
    def on_tool_start(self, tool_name: str, tool_id: str): ...
    def on_tool_complete(self, tool_name: str, tool_id: str, success: bool, result: str): ...
    def on_turn_complete(self, response: dict): ...
    def on_error(self, error: str): ...