
from typing import Protocol

class IMemoryBackend(Protocol):
    def save(self, session_id: str, data: dict) -> None: ...
    def load(self, session_id: str) -> dict | None: ...
    def clear(self, session_id: str) -> None: ...
