"""
Observer base interface.
"""
from typing import Protocol
from enum import Enum

class ToolStartDecision(Enum):
    """Decision before each tool execution."""
    CONTINUE = 0   # proceed with execution
    SKIP = 1       # skip this tool only
    ABANDON = 2    # skip every tool in this turn

class AgentEventObserver(Protocol):
    """Protocol for observing agent events."""
    
    def on_turn_start(self) -> None: ...
    def on_iteration_start(self, iteration: int, max_iterations: int) -> None: ...
    def on_llm_progress(self, info: str) -> None: ...
    def on_tool_start(self, tool_name: str, tool_id: str, tool_arg: str | dict | None = None) -> ToolStartDecision: ...
    def on_tool_complete(self, tool_name: str, tool_id: str, success: bool, result: str) -> None: ...
    def on_turn_complete(self, response: dict) -> None: ...
    def on_error(self, error: str) -> None: ...