"""
Observer base interface.
"""
from typing import Protocol


class AgentEventObserver(Protocol):
    """Protocol for observing agent events."""
    
    def on_turn_start(self) -> None: ...
    def on_iteration_start(self, iteration: int, max_iterations: int) -> None: ...
    def on_llm_progress(self, info: str) -> None: ...
    def on_tool_start(self, tool_name: str, tool_id: str) -> None: ...
    def on_tool_complete(self, tool_name: str, tool_id: str, success: bool, result: str) -> None: ...
    def on_turn_complete(self, response: dict) -> None: ...
    def on_error(self, error: str) -> None: ...